version: '3.8'
services:
  nextjs-app:
    container_name: nextjs-container
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
    #  Development mode environment variables
      - NEXT_PUBLIC_SERVICE_CAMPAIGN=http://localhost:3003
      - NEXT_PUBLIC_SERVICE_REVIEWER=http://localhost:3004
      - NEXT_PUBLIC_SERVICE_CAMPAIGN_DETAIL=http://localhost:3005
      - NEXT_PUBLIC_SERVICE_REVIEWER_DETAIL=http://localhost:3006
      - NEXT_PUBLIC_SERVICE_TRANSACTION=http://localhost:3007
      # Tambahkan variabel lingkungan lain sesuai kebutuhan
    volumes:
      - /app/node_modules
